use_frameworks!

source 'https://github.com/mrachid/SdkNodds.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'Nodds_Example' do
  pod 'Nodds', :path => '../'

  target 'Nodds_Tests' do
    inherit! :search_paths

    
  end
end
